services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
     - 80:80
     - 443:443
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf.d/ssl.conf:/etc/nginx/conf.d/ssl.conf
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/logs:/var/log/nginx

  app:
    build: ./app
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - WDS_SOCKET_PORT=0
    volumes:
      - ./app:/usr/local/src
      - app_node_modules:/usr/local/src/node_modules
  
  api:
    build: ./api
    volumes:
      - ./api:/usr/local/src
      - api_node_modules:/usr/local/src/node_modules

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: waylap
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./data/mysql:/var/lib/mysql
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    command: /bin/bash -c "/usr/share/elasticsearch/data/init.sh & /usr/local/bin/docker-entrypoint.sh"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    restart: always
  
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.17.10
  #   ports:
  #     - 5601:5601
  #   environment:
  #     - ELASTICSEARCH_URL=http://elasticsearch:9200
  #   depends_on:
  #     - elasticsearch


volumes:
  app_node_modules:
  api_node_modules: