services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
     - 80:80
     - 443:443
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf.d/ssl.conf:/etc/nginx/conf.d/ssl.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/logs:/var/log/nginx
      - ./letsencrypt/certbot:/var/www/certbot
      - ./letsencrypt/etc:/etc/letsencrypt

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./letsencrypt/certbot:/var/www/certbot
      - ./letsencrypt/etc:/etc/letsencrypt
      - ./letsencrypt/logs:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  app:
    build: ./app
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/local/src
      - app_node_modules:/usr/local/src/node_modules
  
  api:
    build: ./api
    volumes:
      - ./api:/usr/local/src
      - api_node_modules:/usr/local/src/node_modules

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: waylap
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  app_node_modules:
  api_node_modules: